execute at @e[hasitem=[{item=complementary:meteor_slam_scroll_level_i,location=slot.weapon.mainhand,slot=0}]] run particle complementary:arcane_magic_concentrated ^^^10
execute at @e[hasitem=[{item=complementary:meteor_slam_scroll_level_ii,location=slot.weapon.mainhand,slot=0}]] run particle complementary:arcane_magic_concentrated ^^^10
execute at @e[hasitem=[{item=complementary:meteor_slam_scroll_level_iii,location=slot.weapon.mainhand,slot=0}]] run particle complementary:arcane_magic_concentrated ^^^10
execute at @e[hasitem=[{item=complementary:meteor_slam_scroll_level_iV,location=slot.weapon.mainhand,slot=0}]] run particle complementary:arcane_magic_concentrated ^^^10
execute at @e[hasitem=[{item=complementary:meteor_slam_scroll_level_v,location=slot.weapon.mainhand,slot=0}]] run particle complementary:arcane_magic_concentrated ^^^10
execute at @e[hasitem=[{item=complementary:meteor_slam_scroll_level_vi,location=slot.weapon.mainhand,slot=0}]] run particle complementary:arcane_magic_concentrated ^^^10
execute at @e[hasitem=[{item=complementary:meteor_slam_scroll_level_vii,location=slot.weapon.mainhand,slot=0}]] run particle complementary:arcane_magic_concentrated ^^^10
execute at @e[hasitem=[{item=complementary:meteor_slam_scroll_level_viii,location=slot.weapon.mainhand,slot=0}]] run particle complementary:arcane_magic_concentrated ^^^10
execute at @e[hasitem=[{item=complementary:meteor_slam_scroll_level_ix,location=slot.weapon.mainhand,slot=0}]] run particle complementary:arcane_magic_concentrated ^^^10
execute at @e[hasitem=[{item=complementary:meteor_slam_scroll_level_x,location=slot.weapon.mainhand,slot=0}]] run particle complementary:arcane_magic_concentrated ^^^10
execute at @e[hasitem=[{item=complementary:meteor_slam_scroll_level_i,location=slot.weapon.mainhand,slot=0}]] run particle complementary:arcane_magic_concentrated ^^10^10
execute at @e[hasitem=[{item=complementary:meteor_slam_scroll_level_ii,location=slot.weapon.mainhand,slot=0}]] run particle complementary:arcane_magic_concentrated ^^10^10
execute at @e[hasitem=[{item=complementary:meteor_slam_scroll_level_iii,location=slot.weapon.mainhand,slot=0}]] run particle complementary:arcane_magic_concentrated ^^10^10
execute at @e[hasitem=[{item=complementary:meteor_slam_scroll_level_iV,location=slot.weapon.mainhand,slot=0}]] run particle complementary:arcane_magic_concentrated ^^10^10
execute at @e[hasitem=[{item=complementary:meteor_slam_scroll_level_v,location=slot.weapon.mainhand,slot=0}]] run particle complementary:arcane_magic_concentrated ^^10^10
execute at @e[hasitem=[{item=complementary:meteor_slam_scroll_level_vi,location=slot.weapon.mainhand,slot=0}]] run particle complementary:arcane_magic_concentrated ^^10^10
execute at @e[hasitem=[{item=complementary:meteor_slam_scroll_level_vii,location=slot.weapon.mainhand,slot=0}]] run particle complementary:arcane_magic_concentrated ^^10^10
execute at @e[hasitem=[{item=complementary:meteor_slam_scroll_level_viii,location=slot.weapon.mainhand,slot=0}]] run particle complementary:arcane_magic_concentrated ^^10^10
execute at @e[hasitem=[{item=complementary:meteor_slam_scroll_level_ix,location=slot.weapon.mainhand,slot=0}]] run particle complementary:arcane_magic_concentrated ^^10^10
execute at @e[hasitem=[{item=complementary:meteor_slam_scroll_level_x,location=slot.weapon.mainhand,slot=0}]] run particle complementary:arcane_magic_concentrated ^^10^10